### ISSUE TITLE
Pull request synchronize event warning

### ISSUE THREAD

**Issue by mab68** [trilom/file-changes-action#101]
**Describe the bug**
When a pull-request is updated, it causes a pull-request synchronize event which contains both the before and after values. Which results in this warning being emitted:
```
Received event from pull_request, but also received a before(f4e410346b2c90c44e8f0101f722ee02f3368726) or after(d9ec49f56a56f571782f37de896632a07fd5ed46) value.
 I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
```

**Workflow**
```
name: CI
on: [push, pull_request]
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.1
      - name: Get file changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
```

**Expected behavior**
Expected behavior is the same but without the warning being emitted. 

**Additional context**
Reference #97
