### ISSUE TITLE
ability to output just folders containing changes

### ISSUE THREAD

**Issue by Marcus-James-Adams** [trilom/file-changes-action#115]
Would it be possible to add an option where it could output a  unique list of the folders that contain changed files rather than the files themselves?

We have a number of actions that need to run at the folder level rather than at the file.
currently, I strip off the filename to get the folder however that gives me duplicate folder names (where more than one file has changed within in it) causing my actions to run multiple times within the same folder skewing results.

**Comment by fabiano-amaral** [comment]
I had the same issue, i created a workaround with shell script to "solve"

```yml
job1:
    runs-on: ubuntu-latest
    steps:
     - id: file_changes
       uses: trilom/file-changes-action@v1.2.3

     - name: Get folders
       id: folders
       run: |
        content=$(jq ".[]" $HOME/files.json | sed 's/\/[^/]*$/\//' |  sed -e 's/^"//' -e 's/"$//' | grep '.*\/$' | uniq | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=folders::$content"
    outputs:
      folders: ${{ steps.folders.outputs.folders }}
```
