### ISSUE TITLE
Escaped file names

### ISSUE THREAD

**Issue by peterbe** [trilom/file-changes-action#130]
**Is your feature request related to a problem? Please describe.**
Escaping names. 

Imaging a PR that contains a change to a file that has brackets in it. E.g. `foo-(bar).md`
And in my Actions workflow I do this:
```
  - run: ls ${{ steps.get_diff_files.outputs.files }}
```
what that translates to is:
```
  - run: ls foo-(bar).md
```
which will fail with:
```
no matches found: foo-(bar).md
```

But if it was escaped, it would work:
```
$ touch "foo-(bar).md"
$ ls -l "foo-(bar).md"
-rw-r--r--  1 peterbe  wheel  0 Jan 10 09:52 foo-(bar).md
```

You can't change the workflow Yaml to...
```
  - run: ls "${{ steps.get_diff_files.outputs.files }}"
```
because although `bash` would no longer crash, you'd end up with multiple files being treated as one long string with a space in it. 
E.g. 
```
  - run: ls "foo-(bar).md other.file and/another/file.md"
```

**Describe the solution you'd like**
That the string `outputs.files` escaped each and every file. 
Perhaps something like this:

```yml
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        id: get_diff_files
        with:
          escapeEachFile: true
```

**Describe alternatives you've considered**

**Additional context**
