### ISSUE TITLE
newline support?

### ISSUE THREAD

**Issue by shaunaa126** [trilom/file-changes-action#134]
How can we return the output to be `newline` delimmited? Does the following work?

```
      - name: Get File(s) Changed
        id: files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: '\n'
          fileOutput: '\n'
```
