### ISSUE TITLE
Changes relative to base branch

### ISSUE THREAD

**Issue by srolel** [trilom/file-changes-action#96]
**Is your feature request related to a problem? Please describe.**
I would like to lint only changed files, but lint them from the base branch.

**Describe the solution you'd like**
Omit changes relative to base branch.

**Describe alternatives you've considered**
Squashing when the action runs.

**Comment by trilom** [comment]
Hey @srolel -

I believe what you are talking [about is covered here](https://github.com/trilom/file-changes-action/blob/e320fd20f19a850d6e6a7bbc81a26b5daa830270/README.md#L34-L44) by providing a different `pushBefore` or `pushAfter` SHA, or a seperate `prNumber`.

Some ways I use this are in the [lowest example on the readme](https://github.com/trilom/file-changes-action/blob/e320fd20f19a850d6e6a7bbc81a26b5daa830270/README.md#L172-L202) where I use the `head_commit.id` from the commit to get the commit's PR number (merge request push) and get a list of files.  You can then use that list to perform your action.

**Comment by RayBB** [comment]
The easiest way I've found to do this is in GitHub Actions use the `pull_request` event and `prNumber: ${{ github.event.number }}`

```
name: pre-commit
on:
  pull_request
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        prNumber: ${{ github.event.number }}
        output: ' '
    - uses: pre-commit/action@v2.0.3
      name: mypy
      with: 
        extra_args: mypy --files ${{ steps.file_changes.outputs.files }}

```
